### ISSUE TITLE
Change Name

### ISSUE THREAD

**Issue by judgej** [consilience/iso8583#1]
This fork is `consilience/iso8583` - forked for better control of features and fixes we need. We are using a proprietary caching system (everything rep-cached for production, with no reflection surprises). We are using our own custom schemas, which we cannot include here, but we want our schema to work reliably and that will mean some small changes.

Initial tasks:

* [x] Change root namespace. Also applies to tests, docs etc. Probably `Consilience\Iso8583`?
* [x] Remove absolute dependency on `tightenco/collect`. The risk here is that we are bringing in a package that name clashes with Laravel. Keeping our laravel version and the version of this dependency in sync is a burden we don't want. It could be added as an optional/recommended dependency, if the collection features turn out to be indispensable.
* [ ] The cache manage needs an interface and we need the ability to inject our own cache manager. We will be generating the driving data offline and that data will be incorporated in our release, so we will have a cache manager that supplies the "cached" data from its own source, possibly as a PHP array rather than a JSON string that needs parsing every time we use it.
* [ ] On cache management, a simple API to get at the parsed data - in JSON or as an array - is needed. (Not sure, this may already be built in, but I'm sure it's wrapped inside the cache manager.)
* [x] Hex encoding will be made an option. We are given messages that are NOT hex encoded, so having to encode them, just so this package can decode them, is a step that does not need to happen. Maybe the hex decoding can just be a single step at the start, rather than decoding scattered throughout? I guess there are implications for ISO8583 messages that contain binary data, so make sure we are dealing with non-ml strings here (binary strings).
* [ ] ~~Custom mappers - we do have some fields that need sub-fields extracted. A clean way to do that would be great. It seems a little ad-hoc at the moment.~~
* [x] There is a develop branch in the source package that contains a little refactoring. Check if there are any bug fixes in there that we should also pull in.

We'll get this on composer for the first release, and tidy up the tests a little (so they pass). Also need to test against PHP 7.1 and 7.2

**Comment by barnabaskecskes** [comment]
The `master` branch seems to contain the latest changes from `develop` - I think we are on the latest version and nothing outstanding on the `develop` branch. https://github.com/kaperys/financial/network

**Comment by judgej** [comment]
![image](https://user-images.githubusercontent.com/395934/46146238-2d709c00-c25a-11e8-95c0-371c911ba346.png)

It looks like `develop` has a whole branch of development that has not got merged in. Some may be useful, some may not, it's mainly a bit of insight. I did pull your changes into the master branch.

**Comment by barnabaskecskes** [comment]
It looks that the merging strategy for this lad is a bit of a back-to-front one, and I don't really see clearly. But I've checked the latest commit on `develop` and the changes of that are included in the `master` branch. It seems his master branch does not keep the commit history, in other words squash merging is used: his `master` branch only has 6 commits compared to the 61 commits of the `develop` branch, while the tip of both happened on the same date. That's why I assume that all is included within. 

What's strange is that if you compare the develop to his master branch, it shows changes that are already included on the master branch?! 
Diff: https://github.com/kaperys/financial/compare/develop#diff-22d2a517989c21103c543bb3ea91344f 
Develop: https://github.com/kaperys/financial/blob/develop/src/Message/Packer/MessagePacker.php#L143
Master: https://github.com/kaperys/financial/blob/master/src/Message/Packer/MessagePacker.php#L143

**Comment by judgej** [comment]
Strange. Okay, if the changes are already included, then I guess nothing to see here :-)

**Comment by barnabaskecskes** [comment]
Regarding custom mappers - this package is only concerned with extracting and validating the individual bits. Subfield parsing is the responsibility of the actual schema, so unless we want to add special annotations that can be used in the schema to separate the setters and getters automatically, that task belongs there. (Doing it on the annotation level would be a lot of complexity for no real benefit in my opinion.)

**Comment by judgej** [comment]
If the schema is a class with all that built in, then great, it can be handled there. If some methods are available that can be exposed to help parse those sub-fields (e.g. variable length fields, optional fields) then that would be good. The `substr()` extractions that make assumptions based on which fields we *expect* to be there, and the length we *expect* them to be, when the spec clearly allows fields to be optional and of variable length, leaves me a little uncomfortable. Maybe at a minimum, a validation check of the subfield number and length digits should be performed, just to make sure we have been given what we expect to have been given.

For example we know we can extract '001', ' 993' and '1' from `0010030010020039930030011` based on absolute byte positions. But a confidence check that the fields are named "001", "002" and "003" are where we expect them, and the field lengths "003", "003" and "001" are what we expect, would make me much happier.

**Comment by barnabaskecskes** [comment]
Fair enough. I trusted the documentation on optionals and positions, but further validation won't hurt, I agree.
